from_latest_tag = false
ignore_merge_commits = false
disable_changelog = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = ["git push", "git push origin {{version}}"]
pre_package_bump_hooks = ["cargo set-version -p {package_path} {{version}}"]
post_package_bump_hooks = []

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
cog check
"""

[commit_types]

[changelog]
path = "CHANGELOG.md"

[[changelog.authors]]
signature = "alexandre.falher.pro@gmail.com"
username = "curiousmindflow"

[bump_profiles]

[packages]
troc-core = { path = "troc-core" }
troc-derive = { path = "troc-derive" }
troc = { path = "troc" }
